/** Declaration file generated by dts-gen */

export = wemo_client;

declare class wemo_client {
    constructor(opts: any);

    client(device: any): any;

    discover(cb: any): void;

    getCallbackURL(): any;

    getLocalInterfaceAddress(): any;

    load(setupUrl: any, cb: any): void;

    static DEVICE_TYPE: {
        Bridge: string;
        Dimmer: string;
        HeaterB: string;
        Humidifier: string;
        Insight: string;
        LightSwitch: string;
        Maker: string;
        Motion: string;
        Switch: string;
    };

}

declare namespace wemo_client {
    namespace prototype {
        function client(device: any): any;

        function discover(cb: any): void;

        function getCallbackURL(): any;

        function getLocalInterfaceAddress(): any;

        function load(setupUrl: any, cb: any): void;

        namespace client {
            const prototype: {
            };

        }

        namespace discover {
            const prototype: {
            };

        }

        namespace getCallbackURL {
            const prototype: {
            };

        }

        namespace getLocalInterfaceAddress {
            const prototype: {
            };

        }

        namespace load {
            const prototype: {
            };

        }

    }

}

