/** Declaration file generated by dts-gen */

export = wemo_client;

declare class wemo_client {
    constructor(opts: any);

    client(device: any): any;

    discover(cb: any): void;

    getCallbackURL(): any;

    getLocalInterfaceAddress(): any;

    load(setupUrl: any, cb: any): void;

    static DEVICE_TYPE: {
        Bridge: string;
        Dimmer: string;
        HeaterB: string;
        Humidifier: string;
        Insight: string;
        LightSwitch: string;
        Maker: string;
        Motion: string;
        Switch: string;
    };

}

declare namespace wemo_client {
    
}

